### ISSUE TITLE
genxlate can be inconsistent

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco-mibs#104]
as found with #97 & #100 (new siemens mibs) , it seems that genxlate has strange behaviour.

- when case mismatches duplicate entries can be generated:
  https://github.com/netdisco/netdisco-mibs/blob/447b3d293e4f5a6e4ef9e909824bc8465fd1e7db/EXTRAS/reports/all#L112884-L112887 (since this file is to large i'll paste the segment)
  ```
            hp(11) type=0
            hP(11) type=0
            hp(11) type=0
  ```
  notice the 3 repeating lines which differ only due to case. hp in all lower in several hp mibs, hP is defined only in hp_procurve_420.mib. this was one of the better examples since it has 3 entries for the same enterprise oid mapping.

  other examples are ospfOriginateNewLSAs vs ospfOriginateNewLsas (LSAs vs Lsas)

- items defined in multiple mibs with the same name/oid (case sensitive) can change type:
  - ospfStubTOS is defined as `SYNTAX TOSType` but TOSType differs in definition in both:
    - OSPF-MIB.txt -> `SYNTAX Integer32 (0..30)` with displayhint
    - RFC1253-MIB.my -> `TOSType ::= INTEGER (0..31)` no displayhint
  - this caused reports/all to change
    - from ospfStubTOS(2) type=3
    - to ospfStubTOS(2) type=16 hint=d-0

this seems to be mostly a cosmetic problem with little functional impact other has making mib upgrades confusing sometimes.

**Comment by inphobia** [comment]
seems to be a known issue that net-snmp is not consistent with ordering, namely that is depends on the filesystem to determine order. this seems to explain item 2.

if consensus is that this reports/all is mostly to determine of no vendors overwrite each others oids i'll add that to our wiki.

**Comment by inphobia** [comment]
it seems this could be fixed in net-snmp 5.9:

https://github.com/net-snmp/net-snmp/blob/f9312b44b71ddd247a98c6aff3e986d027e7eaa4/CHANGES#L44-L48

which won't do us much good since they removed the mib chaching feature as well, which breaks mkindex & everything using indexes...

https://github.com/net-snmp/net-snmp/commit/4fd9a450444a434a993bc72f7c3486ccce41f602

**Comment by inphobia** [comment]
#167 was only the groundwork to one day fixing this. reopen

**Comment by ollyg** [comment]
have rewritten all the support scripts so indexes no longer needed
