### ISSUE TITLE
Updated MIBS for Colubris (HP) wireless controller

### ISSUE THREAD

**Issue by def-bs** [netdisco/netdisco-mibs#107]
Hi, I have an issue with a Colubris (HP) wireless controller, ID enterprises.8744.1.47 .

It is not recognized with the correct name.

The MIBS is the following:
(https://github.com/netdisco/netdisco-mibs/files/3599213/mibs-B23594.tar.gz)

Best regards.

**Comment by inphobia** [comment]
unless i'm misreading, 8744.1.47 should alrdy be present in the current mibs:
https://github.com/netdisco/netdisco-mibs/blob/a75a540e2052e9d7ddc58403d0833798bc46f54d/EXTRAS/reports/colubris#L188

but these mibs are newer as the ones we currently have, so i'll try & get them imported. shouldn't be that hard but it seems they did remove 1 device id, so i'll need to readd that before i import this.

**Comment by inphobia** [comment]
#109 created, but need input from our hp guru.

**Comment by def-bs** [comment]
Is there any news about this MIBS?

It doesn't seem to work.

For MSM765 I am still getting unknown / enterprises.8744.1.47 as Vendor / Model.

Is there something that I can do?

Thank you a lot

**Comment by inphobia** [comment]
well, right now i'm waiting for some feedback on these mibs, once that's cleared we'll merge them into our main mib repo.

then we'll need to figure out if these devices can be queried with an existing snmp::info class or if we need to write a new one.

**Comment by JeroenvIS** [comment]
MIBs in #109 are OK. Next step would be to write a device class for Colubris...

**Comment by inphobia** [comment]
the colubrus mibs have been compared & the most recent versions merged.

the hp ones which were included we did not add, since they weren't needed. if you need those however feel free to open a new issue for them.
