### ISSUE TITLE
MIB For FortiSwitch

### ISSUE THREAD

**Issue by gmourani** [netdisco/netdisco-mibs#114]
Hello,

In the latest version, I can't any MIB related to FortiSwitch !

Regards,

**Comment by inphobia** [comment]
most likely since noone submitted one and snmp::info has no specific support for that product :)

on the other hand, i am a fortinet customer for other devices. so i've just downloaded the 6.2.3 fortiswitch mib and will see if it can be added.

**Comment by inphobia** [comment]
reminder: upgrade fortithingies mibs

**Comment by inphobia** [comment]
#153 created & will be merged soon

**Comment by inphobia** [comment]
updated, new mibs release in the next 10 days
