### ISSUE TITLE
ExtemeNetworks updated MIB

### ISSUE THREAD

**Issue by Disco402** [netdisco/netdisco-mibs#118]
Hello All,

Could we get an updated MIB for Extreme switching. I have found 

https://jira.observium.org/secure/attachment/15732/16.2.4.5-patch1-6_MIB.txt 

Which seems to have the correct products in it. I am trying to source the latest MIBs from extreme.

Thanks

**Comment by Disco402** [comment]
[16.2.5.4-patch1-25_MIB.txt](https://github.com/netdisco/netdisco-mibs/files/5000011/16.2.5.4-patch1-25_MIB.txt)
[30_7_1_1_MIB.txt](https://github.com/netdisco/netdisco-mibs/files/5000012/30_7_1_1_MIB.txt)

**Comment by Disco402** [comment]
Pull request created #119

**Comment by inphobia** [comment]
reviewed but have a few questions as mentioined in https://github.com/netdisco/netdisco-mibs/issues/124

i'll try & sort it in the coming days.

**Comment by inphobia** [comment]
30.7.1.1 mib added in #157 

i think 16.2.5.4 should also be addressed by that, if not please open a new issue
