### ISSUE TITLE
Adding Aruba 6300M..

### ISSUE THREAD

**Issue by mirktmirkt** [netdisco/netdisco-mibs#120]
Hello,

This is my first time I am trying to add new MIBs, so (in advance) sorry for stupid questions..

We have got some Aruba 6300M switches.. Netdisco (2.46.1 on Debian 10.5..) identifies them as:
Vendor: unknown
Model: enterprises.47196.4.1.1.1.100

I have tried adding:
https://asp.arubanetworks.com/downloads/software/RmlsZTo3OTllOThkYS1jNmJjLTExZWEtYjY3Mi0yZjExZWNkMjNjYmY%3D
Direct URL of MIBs:
http://h30326.www3.hpe.com/hpn/ArubaOS-CX_10.05_MIBs_8th_Jul2020.tar?merchantId=ASP_DROPBOX
by following steps:
https://github.com/netdisco/netdisco-mibs/wiki/Updating-MIBs

All the steps were successful.. I have updated ~netdisco/netdisco-mibs , but netdisco still shows unknown enterprises.47196.4.1.1.1.100..

Any ideas what have I missed?

Thank you in advance!

**Comment by inphobia** [comment]
well, netdisco is made up of 3 main componenent:
 * netdisco
 * snmp::info
 * netdisco-mibs


vendor/os detection is done by snmp::info, and after a quick glance at https://github.com/netdisco/snmp-info/blob/master/lib/SNMP/Info.pm it might be that snmp::info just isn't registering your switches.

if we are lucky then perhaps we can plug them into an existing snmp::info module and get it working, if unlucky we might need to write a new snmp;;info module.

the easiest way to figure that out is by following https://github.com/netdisco/snmp-info/wiki/Simulating-Agents#get-snmp-datadump & providing us the snmpsim/rec dumps.


i've added updating the aruba mibs to my todo list.

**Comment by inphobia** [comment]
added in pull request #138 , all testing welcome.

**Comment by JeroenvIS** [comment]
> well, netdisco is made up of 3 main componenent:
> 
>     * netdisco
> 
>     * snmp::info
> 
>     * netdisco-mibs
> 
> 
> vendor/os detection is done by snmp::info, and after a quick glance at https://github.com/netdisco/snmp-info/blob/master/lib/SNMP/Info.pm it might be that snmp::info just isn't registering your switches.
> 
> if we are lucky then perhaps we can plug them into an existing snmp::info module and get it working, if unlucky we might need to write a new snmp;;info module.

FWIW: I have "writing an SNMP::Info module for Aruba AOS-CX switches" on my ToDo-list @ work. It's a sub-task of "Getting proper support for Aruba AOS-CX switches in Netdisco" :-)

It has some level of priority, I actually hope to have an initial, working version before end of the year.

**Comment by Chromy29FR** [comment]
Hi, any update on this ? Just installed netdisco for aruba to replace switchmap but switches (6300M/8360) still not discovered.
I can provide files from Aruba if needed. 
Regards

**Comment by inphobia** [comment]
mibs have been merged.

i see @JeroenvIS has started work on the snmp::info class. i'll see if i can get most of my of changes committed over the following week & then release a new mib package.

**Comment by inphobia** [comment]
merged, new mibs release coming shortly.

should i have missed something feel free to open a new issue.
