### ISSUE TITLE
Please add support for Aruba CX switches.

### ISSUE THREAD

**Issue by null999-a** [netdisco/netdisco-mibs#122]
It would be awesome if you guys could add support for Arubas CX switches, especially:

Name: arubaWiredSwitchJL479A!@#.iso.org.dod.internet.private.enterprises.hpe.hpeNetworking.wiredNetworkingDevices.arubaOS-CX.wndDeviceIds.arubaWiredSwitchJL479A
OID: .1.3.6.1.4.1.47196.4.1.1.1.2
MIB: ARUBAWIRED-NETWORKING-OID
Desc: JL479A Aruba 8320 48p 10G SFP/SFP+ and 6p 40G QSFP+ chassis switch.

Attached are the latest MIBs for:
Aruba CX - ArubaOS-CX_10.05_MIBs_8th_Jul2020.zip
Aruba/HPE switches - mibs-Apr-2020.zip
Aruba instant Access Points - aruba-instant-mibs_8.7.0.0_75915.zip
Aruba mobility controllers - aruba-mibs_8.7.0.0_75916.zip

Thank you!
[ArubaOS-CX_10.05_MIBs_8th_Jul2020.zip](https://github.com/netdisco/netdisco-mibs/files/5128127/ArubaOS-CX_10.05_MIBs_8th_Jul2020.zip)
[mibs-Apr-2020.zip](https://github.com/netdisco/netdisco-mibs/files/5128128/mibs-Apr-2020.zip)
[aruba-instant-mibs_8.7.0.0_75915.zip](https://github.com/netdisco/netdisco-mibs/files/5128130/aruba-instant-mibs_8.7.0.0_75915.zip)
[aruba-mibs_8.7.0.0_75916.zip](https://github.com/netdisco/netdisco-mibs/files/5128131/aruba-mibs_8.7.0.0_75916.zip)

**Comment by inphobia** [comment]
thx for posting these, i'll add them to my todo list.

do keep in mind that this might that a while, it seems they include all rfc etc mibs as well which i'll need to clean out first & then check for breakage.

**Comment by inphobia** [comment]
"ArubaOS-CX_10.05_MIBs_8th_Jul2020.zip" should have been added in #138 

"aruba-instant-mibs_8.7.0.0_75915.zip" & "aruba-mibs_8.7.0.0_75916.zip" also have newer versions added in #138 

the hp stuff ("mibs-Apr-2020.zip") could be in use of an update perhaps.

**Comment by inphobia** [comment]
all mibs are good to go, expect a new netdisco-mibs release in the next 10 days.

snmp::info support is in the works, but not by me.
