### ISSUE TITLE
New Aruba MIBS

### ISSUE THREAD

**Issue by FabioPedretti** [netdisco/netdisco-mibs#126]
Aruba MIBS were already updated for 14e82dd80f5c4b0fdc7101bf53499546a3e9a50b, but we have again new APs. Attached the MIBS with the new entries.
Thanks.

[aruba-instant-mibs_8.7.1.0_77203.tar.gz](https://github.com/netdisco/netdisco-mibs/files/5432596/aruba-instant-mibs_8.7.1.0_77203.tar.gz)

**Comment by FabioPedretti** [comment]
Specifically, while last update included many missing Aruba access point, apProducts.111 (ap505) is still missing and is included in file attached.

**Comment by inphobia** [comment]
i created pull request #138 for this, but there are some changes that i'm not 100% with. care to test it out & see if there are any regressions?

**Comment by inphobia** [comment]
has been merged!
