### ISSUE TITLE
Documentation nit I think, 'ignore' or 'skip'?

### ISSUE THREAD

**Issue by jrbinks** [netdisco/netdisco-mibs#141]
https://github.com/netdisco/netdisco-mibs/wiki/Updating-MIBs

section 8: Items marked ⚠ will be put in the "ignore" folder and skipped.

Is the "ignore" folder here the one that is named "skip"?  If so, wouldn't it be better to reference it so?

**Comment by inphobia** [comment]
you are correct.
fixed https://github.com/netdisco/netdisco-mibs/wiki/Updating-MIBs & https://github.com/netdisco/netdisco-mibs/wiki/Maintenance-Scripts

thx
