### ISSUE TITLE
IBM / Lenovo G8000-G8264 MIBs

### ISSUE THREAD

**Issue by jmp242** [netdisco/netdisco-mibs#15]
The current IBM Mibs don't seem to work for getting LLDP neighboors from any IBM / Lenovo G8000, G8124 or G8264 switch. I'm attaching currentish MIBs for inspection.

**Comment by jmp242** [comment]
[Uploading G8264-7.9.17.MIBS.zip…]()
[G8052MIBs.zip](https://github.com/netdisco/netdisco-mibs/files/893760/G8052MIBs.zip)
[G8124MIBs.zip](https://github.com/netdisco/netdisco-mibs/files/893763/G8124MIBs.zip)

**Comment by ollyg** [comment]
Hi @jmp242, many thanks, and with the help of @hanserasmus we have netdisco-mibs release 3.8 out with these updates. Please run netdisco-deploy or download the release from https://github.com/netdisco/netdisco-mibs/releases
