### ISSUE TITLE
Mibs for Microsens (enterprises 3181)

### ISSUE THREAD

**Issue by Thilroy** [netdisco/netdisco-mibs#164]
Hi,
Here at the ULB (Université Libre de Bruxelles), we're using an awful lot of Micro-switches from the German company Microsens.
We find Netdisco very useful to locate clients by IP/Mac address across our network and would very much like being able to discover the client addresses in the MAC tables of our Microsens switches.
Could it be possible to integrate Microsens Mib files into Netdisco ?
I'll attach the Mib files received from microsens, even if I'm not sure they got everything.
Thanks in advance,
Thierry

[msswitch30v2.zip](https://github.com/netdisco/netdisco-mibs/files/6571053/msswitch30v2.zip)
[msswitch30v1.zip](https://github.com/netdisco/netdisco-mibs/files/6571054/msswitch30v1.zip)
[MICROSENS-G6-MIB.mib.zip](https://github.com/netdisco/netdisco-mibs/files/6571059/MICROSENS-G6-MIB.mib.zip)

**Comment by Thilroy** [comment]
Has anybody had a look at it ? If I can do anything, pls let me know. Thanks in advance.

**Comment by ollyg** [comment]
Looks like v1 is just older version of v2, and they are same MIB module:

> ✘ error: from microsens/msswitch30v1.mib is defined differently in microsens/msswitch30v2.mib

The rest seems OK, we have `MICROSENS-G6-MIB` already and I've added the new `MS-SWITCH30-MIB`

> 👀 Scanning submitted files
👀 Building MIBs baseline
✔ Index rebuilt (0 errors, 99 vendors, 4525 mibs).
< MICROSENS-G6-MIB is older (201505221058 < 201802121619) (MICROSENS-G6-MIB.mib ⇰ older/MICROSENS-G6.mib)
⭑ MS-SWITCH30-MIB (msswitch30v2.mib ⇰ MS-SWITCH30-MIB.mib)
✔ MIBs ready for import.

**Comment by ollyg** [comment]
thanks, added in commit  df232fa

**Comment by dsdwn** [comment]
Hello,

I'm running:
Software	Version
App::Netdisco	2.61.1
SNMP::Info	3.92
DB Schema	78
PostgreSQL	13.00.11
Perl	5.32.1

installed from automated install-script ...

in inventory the G6 switches are shown as:
Vendor	    Model	          Count
unknown	    enterprises.3181.10.6         106

microsens-mibs are avail in:
/home/netdisco/netdisco-mibs#

Ports and Vlans are properly read from the device, but no nodes are show at the ports section ?

Any advice ?
Thanks in advance

Esteban

**Comment by dsdwn** [comment]
while discoery, lldp-section is also throwing notices ... 

`netdisco@nodex:~$ ~/bin/netdisco-do discover -d  x.x.x.x
[108106] 2023-05-22 17:37:55  info App::Netdisco version 2.061001 loaded.
[108106] 2023-05-22 17:37:55  info discover: [x.x.x.x] started at Mon May 22 19:37:55 2023
Use of uninitialized value $proto in numeric eq (==) at /home/netdisco/perl5/lib/perl5/SNMP/Info/LLDP.pm line 450.
Use of uninitialized value $proto in numeric eq (==) at /home/netdisco/perl5/lib/perl5/SNMP/Info/LLDP.pm line 455.
Use of uninitialized value $proto in numeric eq (==) at /home/netdisco/perl5/lib/perl5/SNMP/Info/LLDP.pm line 461.
Use of uninitialized value $proto in numeric eq (==) at /home/netdisco/perl5/lib/perl5/SNMP/Info/LLDP.pm line 450.
Use of uninitialized value $proto in numeric eq (==) at /home/netdisco/perl5/lib/perl5/SNMP/Info/LLDP.pm line 455.
Use of uninitialized value $proto in numeric eq (==) at /home/netdisco/perl5/lib/perl5/SNMP/Info/LLDP.pm line 461.
[108106] 2023-05-22 17:38:49  info discover: finished at Mon May 22 19:38:49 2023
[108106] 2023-05-22 17:38:49  info discover: status done: Ended discover for x.x.x.x
netdisco@nodex:~$`

**Comment by dsdwn** [comment]
obviously something wrong deep under hood with the G6-mib files; unable to load with net-snmp stack
