### ISSUE TITLE
Sophos XG MIBS

### ISSUE THREAD

**Issue by jsrcomp** [netdisco/netdisco-mibs#170]
Is it possible to add some Sophos products?

XG Series (covers v17 and v18): 
[SOPHOS-XG-MIB.zip](https://github.com/netdisco/netdisco-mibs/files/7126662/SOPHOS-XG-MIB.zip)
Serial Number is listed here:  .1.3.6.1.4.1.2604.5.1.1.4 (sfosDeviceAppKey)

**Comment by ollyg** [comment]
thanks! added in 4.024

**Comment by ollyg** [comment]
If you need support in Netdisco, please create a ticket here for the vendor platform: (serial number etc)
https://github.com/netdisco/snmp-info/issues/new
