### ISSUE TITLE
MIBS for Siemens Ruggedcom

### ISSUE THREAD

**Issue by nicolasbussieres** [netdisco/netdisco-mibs#175]
Need to add support for Siemens Ruggedcom switches

**Comment by ollyg** [comment]
Hi @nicolasbussieres for this we'll need a copy of the MIB files - are you able to download them from the vendor site and share? Thank you.

**Comment by nicolasbussieres** [comment]
I think the following mib should give all the necessary information for the
vendor and models (RcMainBoard)

I can provide all the mibs if required

**Comment by ollyg** [comment]
Sorry @nicolasbussieres I do not see the file? Please attach to a new ticket if you can.
