### ISSUE TITLE
Update Huawei MIBs

### ISSUE THREAD

**Issue by mkesoulis** [netdisco/netdisco-mibs#177]
Please update the HUAWEI-MIB file. I am attaching a file I found
[HUAWEI-MIB.txt](https://github.com/netdisco/netdisco-mibs/files/8003159/HUAWEI-MIB.txt)
.

**Comment by ollyg** [comment]
Hi @mkesoulis many thanks for this!
We had a duplicate ticket and have now updated Huawei mibs recently.
