### ISSUE TITLE
Mibs for Zyxel Switches

### ISSUE THREAD

**Issue by danielhainich** [netdisco/netdisco-mibs#179]
Hi,
is it possible to add the MIBs for some/all Zyxel-Switches? 

Thanks
Daniel

**Comment by ollyg** [comment]
Hi @danielhainich yes sure, if you can obtain them and attach to a ticket. Many thanks!

**Comment by sibelle-labs** [comment]
[GS1900-series-v2_10.zip](https://github.com/netdisco/netdisco-mibs/files/14116128/GS1900-series-v2_10.zip)
