### ISSUE TITLE
Fiberstore MIBs (fs.com)

### ISSUE THREAD

**Issue by Stoatwblr** [netdisco/netdisco-mibs#184]
FS.com have a fairly extensive range of switches which "aren't quite" fully detected correctly by ND

The MIBfiles are downloadable from their website (probably some overlap in these)

https://img-en.fs.com/file/user_manual/s5860-series-swithes-snmp-mib-files.zip
https://img-en.fs.com/file/user_manual/n5860-and-n8560-series-swithes-snmp-mib-files.zip
https://img-en.fs.com/file/user_manual/s3910-series-swithes-snmp-mib-files.zip

I've asked them to make contact and submit their MIBs directly

**Comment by ollyg** [comment]
Hi @Stoatwblr will close as we have #187 open now

**Comment by inphobia** [comment]
since #187 has been stalled for a while i wonder if you still have a contact at fiberstore who can provide us with the latest version of their mibs.
