### ISSUE TITLE
Cisco MIBs out of date in netdisco-mibs. Could be causing issues with mac suck/walk

### ISSUE THREAD

**Issue by decalv** [netdisco/netdisco-mibs#185]
Noticed that our Cisco switches with 16.x IOS version had mac walk/suck working, but the 17.x IOS versions weren't. When the 16.x were updated to 17, mac walk/suck stopped working on them also.

Could be due to out of date MIBs? Noticed that there are new versions out.

**Comment by JeroenvIS** [comment]
This is likely not an issue with MIBs being outdated, but code changes in IOS that might need workarounds in SNMP::Info classes used for Cisco.
Please file a bug for the SNMP::Info class, preferably with 'netdisco-do' outputs for a successful macsuck against 16.x and a failed macsuck against 17.x.

**Comment by eldecal** [comment]
Awesome, thank you @JeroenvIS
