### ISSUE TITLE
Infrapower MIB (Austin-hughes)

### ISSUE THREAD

**Issue by Stoatwblr** [netdisco/netdisco-mibs#188]
[IPD-03-S-firmware.zip](https://github.com/netdisco/netdisco-mibs/files/9065887/IPD-03-S-firmware.zip)

Attached is the MIB for Austin-Hughes "Infrapower" intelligent ATS/PDU - v4.4.0
It'd be great to see this rolled in

**Comment by ollyg** [comment]
Hi @Stoatwblr this looks like a firmware file, not a MIB?
