### ISSUE TITLE
FortiManager VM platform detection incorrect

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco-mibs#190]
ND 2.52.8

We have a fortimanager VM

Netdisco shows it in the inventory/platform summary as

fortinet / fortinet.103.1.64

We also have a forigate VM instance running which shows up as

fortinet / VM64

This would be my suggestion as the correct alternative.

Thanks!

**Comment by kingtrw** [comment]
[FORTINET-FORTIMANAGER-FORTIANALYZER-MIB-build2473.zip](https://github.com/netdisco/netdisco-mibs/files/9190675/FORTINET-FORTIMANAGER-FORTIANALYZER-MIB-build2473.zip)

Here's a MIB!

**Comment by ollyg** [comment]
thanks!  have released 4.033
