### ISSUE TITLE
Fortinet Fortigate MIB update (taken from FortiOS 6.4.9)

### ISSUE THREAD

**Issue by jpvelders** [netdisco/netdisco-mibs#191]
Hi,

I succesfully updated the fortinet-fortigate-mib.mib with attached patch to contain the updates from FortiOS 6.4.9, retaining all former model numbers if I followed the instructions correctly.

-jpv
[netdisco-snmp-mibs-fortinet-649.patch.txt](https://github.com/netdisco/netdisco-mibs/files/9236808/netdisco-snmp-mibs-fortinet-649.patch.txt)

**Comment by ollyg** [comment]
thanks! Have released 4.032
