### ISSUE TITLE
Extreme Wireless WiNG

### ISSUE THREAD

**Issue by ryanlenard** [netdisco/netdisco-mibs#192]
[AP7562-mibs-5.9.8.3-003R.tar.gz](https://github.com/netdisco/netdisco-mibs/files/9262853/AP7562-mibs-5.9.8.3-003R.tar.gz)

Extereme Wireless WiNG AP's (Ex Motorola and Zebra)

**Comment by ollyg** [comment]
many thanks @ryanlenard !
And sorry for the extremely long wait (no pun intended)
this is added in commit f7ccdd5
