### ISSUE TITLE
Add Aruba/Silverpeak SDWAN Mibs to netdisco

### ISSUE THREAD

**Issue by alcatron** [netdisco/netdisco-mibs#197]
Would it be possible to add the following Aruba/Silverpeak SDWAN mibs to netdisco?

Thanks!
[mibs-9.2.zip](https://github.com/netdisco/netdisco-mibs/files/10941522/mibs-9.2.zip)

**Comment by ollyg** [comment]
many thanks @alcatron !
Have added this in commit 2d13353

**Comment by alcatron** [comment]
Can you add these updated mibs 9.5 ?
[mibs-9.5.zip](https://github.com/user-attachments/files/16277981/mibs-9.5.zip)
