### ISSUE TITLE
Add Megatec snmp network card for some UPS (Upsmate.mib)

### ISSUE THREAD

**Issue by alexthenorth** [netdisco/netdisco-mibs#199]
[mibs.zip](https://github.com/netdisco/netdisco-mibs/files/11119152/mibs.zip)

**Comment by ollyg** [comment]
many thanks @alexthenorth !
I've added this as vendor megatec in commit 2eab77a

**Comment by alexthenorth** [comment]
@ollyg thanks so much, i updated NetDisco, but...
Vendor / Model | unknown         /         enterprises.935.1.1.1
