### ISSUE TITLE
Vendor Huawei : model not parsed correctly for S573X

### ISSUE THREAD

**Issue by Ddvinfo** [netdisco/netdisco-mibs#202]
Hello,

we have trouble with some huawei devices details : 
- some are discovered and details are ok : S5700, S5720

- some are dicovered and details are not ok : 
  -  S5731 : 
![hw-s5731](https://github.com/netdisco/netdisco-mibs/assets/139756646/15509f27-00e3-4f49-ade3-a7905d87ae04)
  - S5735 : 
 ![hw-s5735](https://github.com/netdisco/netdisco-mibs/assets/139756646/c49991eb-a569-451c-8fd9-44115983756f)
 
Obviously model and layer 7 capabilities are not ok

Here are the mibs of the equipments
[hw-mib.zip](https://github.com/netdisco/netdisco-mibs/files/12067898/hw-mib.zip)

**Comment by ollyg** [comment]
thanks @Ddvinfo this is merged in 5157ea1 
I cannot say if this fixes your issues with model and layer, until we release and test of course.

**Comment by Ddvinfo** [comment]
thanks Oliver for your work on this ticket :)
Lots of new huawei devices are included in this patch, so let's be confident on the result !

**Comment by ollyg** [comment]
If you run netdisco-deploy now, and select "y" to update mibs it should bring them in. The mibs bundle is released.
