### ISSUE TITLE
Adding new MIB files for Transition Network

### ISSUE THREAD

**Issue by gmourani** [netdisco/netdisco-mibs#208]
Hello,

Attached are tree MIBs files for Transition Network, thanks (I changed the extension from mid to txt).

[SISGM1040-284-LRT_v7.20.0121.txt](https://github.com/netdisco/netdisco-mibs/files/12835710/SISGM1040-284-LRT_v7.20.0121.txt)
[SISPM1040-582-LRT_VB7.20.0121.txt](https://github.com/netdisco/netdisco-mibs/files/12835711/SISPM1040-582-LRT_VB7.20.0121.txt)
[SM16TAT2SA_v1.04.0059.txt](https://github.com/netdisco/netdisco-mibs/files/12835712/SM16TAT2SA_v1.04.0059.txt)

**Comment by ollyg** [comment]
Thanks @gmourani !
I have added these and released version 4.038 of the mibs.
