### ISSUE TITLE
Vendor RADwin : model not parsed correctly for RW5000

### ISSUE THREAD

**Issue by dev-osuri** [netdisco/netdisco-mibs#213]
Hello,

We have trouble with some RADWIN devices details :

![image](https://github.com/netdisco/netdisco-mibs/assets/148187807/18704459-e39a-466c-b6c2-cad66a57e300)

Here are the mibs of the equipments:
[MIB_5.1.43_ver_11_0_78_06.zip](https://github.com/netdisco/netdisco-mibs/files/13509817/MIB_5.1.43_ver_11_0_78_06.zip)

**Comment by inphobia** [comment]
seems to be a trivial mib to add, but snmp::info does not have support for this device, so even with the mib it most likely won't change the behaviour.

adding an snmp::info module is most likely needed. regretfully i don't think i'll be able to make to for that part in the near future, but i made a basic writeup in this issue:
https://github.com/netdisco/netdisco-mibs/issues/212

mib shouldn't be a challenge, i'll assign that part to myself

**Comment by inphobia** [comment]
mibs added, if only they were all this simple

https://github.com/netdisco/netdisco-mibs/pull/225
