### ISSUE TITLE
rename silver-peak to silverpeakNW 

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco-mibs#226]
this one isn't used yet - consider renaming the directory to silverpeaknw to match the module-identity.

https://github.com/netdisco/netdisco-mibs/blob/33dad33364eb4bb6c38ecae268577737f65ee403/silver-peak/SILVERPEAK-SMI.mib#L19-L28

**Comment by ollyg** [comment]
the directory name isn't used anywhere but there seems to be a form of lowercase and meaningful names for us maintainers, rather than using the module name. I'll close this but thanks for the suggestion!
