### ISSUE TITLE
Compare MIBS

### ISSUE THREAD

**Issue by hanserasmus** [netdisco/netdisco-mibs#30]
I am not sure how to check which version of a mib is newer.  I have found the issue where our HP MCS devices would pick up as enterprise232 in the inventory list, where I would like to have it show up as HP, and the device model MCS and whatever else could be discovered. I have found a mib with a similar name, but not sure how to see which one is newer, netdisco's or the one I found [here](https://github.com/taishin/vendor_mibs/blob/master/cpqhost.mib) . I know this is strictly not an "issue" but this is the only way for others to find this topic if they were in the same situation.

**Comment by JeroenvIS** [comment]
It's common for MIBs to contain a MODULE-IDENTITY section with a LAST-UPDATED stanza; often a big part of the revision history is also included. [This](https://github.com/netdisco/netdisco-mibs/blob/master/hp/hpicfdownload.mib#L35) is a nice example.

The CPQHOST-MIB doesn't have that info, so one has to look at the diffs between copies and try to deduce which one is newer. In your example, the MIB that you found appears to be a few versions more recent, as it contains more objects and the comments about cpqHoMibRevMinor version indicate (to humans) that this object relates to MIB revision numbers.

I hope that answers your question as to comparing MIBs. Regarding your HP MCS devices showing up as enterprise.232: assuming that that's in Netdisco, that warrants another ticket. It would be good to know what device class Netdisco reports for the HP MCS, I expect a rather generic one like Info::Layer2 or Info::Layer3. I expect a new SNMP::Info device class is needed for these devices to have more details in the inventory.

**Comment by hanserasmus** [comment]
@JeroenvIS Thank you.  Should I then download the MIB I found, delete the one from the original netdisco-mibs directory, and create a pull request to have netdisco-mibs updated?

I shall create a ticket for the MCS devices.

**Comment by hanserasmus** [comment]
I tried updating the mib cpqhost.mib with the one I found in post number 1. But I get the following error:
✘ CPQHOST-MIB has no parseable revision date (in 'cpqhost-mib.mib')
Not sure how to proceed to try and fix this. Obviously I cannot just add a revision date.

**Comment by ollyg** [comment]
If you are confident that the MIB is useful and usable and perhaps it replaces a MIB also missing a date, then you can copy it back out of the "error" folder. When you run importmibs, it will be copied over.
