### ISSUE TITLE
Why would a mib be skipped during prepmibs process?

### ISSUE THREAD

**Issue by hanserasmus** [netdisco/netdisco-mibs#32]
Hi 

[This](https://github.com/netdisco/netdisco-mibs/wiki/Updating-MIBs) links relates.

Why would the process prepmibs place a MIBs file in a "skipped" folder? What is wrong with the file for this to happen? I am attaching the file being skipped by the process, so that someone with more knowledge could maybe tell me what is wrong. (I only added the .txt extension to be able to upload the file)

Regards

Hans

[BROTHER-MIB.mib.txt](https://github.com/netdisco/netdisco-mibs/files/1251485/BROTHER-MIB.mib.txt)

**Comment by JeroenvIS** [comment]
When I open the text file that you attached, I receive a document with HTML content, so not a plain text MIB file. Could that be the issue? Can you verify the source file that you're processing with a text editor, and double-check that it's in plain text?

**Comment by hanserasmus** [comment]
Closing this because of my own bloody stupidity. Sorry to have bothered with nonsense. You were right, something went wrong with the downloading of the MIB file, it created HTML i.s.o txt, and that was the issue. Sorry again!
