### ISSUE TITLE
NetVanta 1550-24P not mibs

### ISSUE THREAD

**Issue by reabiliti** [netdisco/netdisco-mibs#34]
Good afternoon,
appeared in the presence of a new vendor. It is possible to add mib for the AdTran NetVanta 1550-24P. Mac addresses are not defined on ports.

![image](https://user-images.githubusercontent.com/30253042/30470174-558d4ab2-99fc-11e7-8664-043816ee20e7.png)

![image](https://user-images.githubusercontent.com/30253042/30470115-1fed4704-99fc-11e7-85cb-645e50e217ae.png)

**Comment by hanserasmus** [comment]
I see one can get the MIBS from [here](https://adtran.com/web/fileDownload/doc/24937) but that is only half the problem solved. The developers will then need to edit the code as well as far as I know. I will try and add the MIBS so long, and then the rest could follow? But that is all up to the devs.

**Comment by reabiliti** [comment]
Good afternoon,
Thank you very much, we will wait. Do you need to create another query? Or is this enough for developers? :)

**Comment by ollyg** [comment]
We probably do need an snmp walk from the device to find out where the MAC addresses (and better port names) are located. I need to find out that command...

**Comment by ollyg** [comment]
Well the MIBs are in and working but I think adtran are doing something strange.

Given `enterprises.664.1.1399` I would imagine the 1399 to be an OBJECT-IDENTIFIER however it seems to be a TEXTUAL-CONVENTION in ADTRAN-TC. However ADTRAN-TC is not loaded by other MIBs so I wonder whether we need to do work in SNMP::Info to resolve the product name from the OID via the TC.
