### ISSUE TITLE
Brocade VDX devices detected as Vendor "unknown" Model "enterprises.1588.3.3.1.X"

### ISSUE THREAD

**Issue by nomisunrider** [netdisco/netdisco-mibs#36]
This is a follow on to https://github.com/netdisco/snmp-info/issues/208 for SNMP-INFO, which looks to have been attempted to address here.

After the latest update of netdisco-mibs, there is no change in detection of Brocade VDX devices.

See example screenshot of how my VDX systems are detected:

![image](https://user-images.githubusercontent.com/13275125/30597203-f13f2328-9d1b-11e7-9346-9911f7c6f6f1.png)

**Comment by ollyg** [comment]
I have added a script to [netdisco/netdisco-mibs] that locates these in the MIBs:

```
$> EXTRAS/scripts/translateleaf foundry enterprises.1588.3.3.1.1000
≈ translating for 'foundry'
BROCADE-PRODUCTS-MIB::vdx8770S4
⚑ Translate done.
```

This indicates we need to load `BROCADE-PRODUCTS-MIB` in the device class. Which device class is used for these devices?

**Comment by JeroenvIS** [comment]
@nomisunrider Can you please click through to one of those devices, look at the "Details" tab and let us know what Netdisco reports as "SNMP Class"?

**Comment by nomisunrider** [comment]
@JeroenvIS 
It shows as  SNMP::Info::Layer3

**Comment by nomisunrider** [comment]
I'll try deleting a device and rediscovering it to see if it uses a different class.

**Comment by nomisunrider** [comment]
I deleted one of the devices, then discovered it and it is still showing up with SNMP Class SNMP::Info::Layer3

**Comment by JeroenvIS** [comment]
OK, thanks for the feedback, that's what I was afraid of.
Then I guess someone needs to create a new device class for these in SNMP::Info. And we currently don't have many people working on that.

I may have time to do that in ~ 3 weeks or so (at least a simple base class that will remove the "unknown" and that can translate the model names).

**Comment by ollyg** [comment]
Commit e2b6880 in SNMP::Info enables use of Layer3::Foundry class for enterprises.1588 and loads BROCADE-PRODUCTS-MIB. Hopefully this improves things.
