### ISSUE TITLE
Motorola AP 6532 not correctly detected

### ISSUE THREAD

**Issue by gabbiere** [netdisco/netdisco-mibs#37]
Dear all,

with reference to the issue #340 in netdisco, ollyg wrote: 

> it looks like we need some updated MIBs in [netdisco-mibs] for this platform, as my test does not resolve the device ID to a product name:
> $> EXTRAS/scripts/translateleaf enterprises.388.50.1.1.4
> ≈ translating for 'all'
> SNMPv2-SMI::enterprises.388.50.1.1.4
> ⚑ Translate done.
> Are you able to download vendor mibs under a support contract and share them? If so, please open a ticket at https://github.com/netdisco/netdisco-mibs/issues/new.

Here enclosed are the most recent MIBs available from Extreme Networks now supporting the former Motorola - Symbol APs

Thank you very much and best regards 

[extreme networks.zip](https://github.com/netdisco/netdisco-mibs/files/1340785/extreme.networks.zip)

**Comment by JeroenvIS** [comment]
I had a look at the MIBs, but the new WS-MIB is completely different from the existing one. We would lose object translations if we just replaced it.
It will probably require some careful manual merging :-(

**Comment by gabbiere** [comment]
Dear Jero,

I think I could help with a little guidance, since I have some working knowledge of SNMP.  
Are there  relevant HOWTOs or documentation for correctly producing and testing files for netdisco-mibs?
Do I need to merge the extreme-networks MIBs each with the MIB of the same name under motorola?
Do I need to add/change records in oui table?
Thank you very much and best regards

**Comment by ollyg** [comment]
Hi @gabbiere please follow this guide here for the Motorola MIBs update:
https://github.com/netdisco/netdisco-mibs/wiki/Updating-MIBs

**Comment by ollyg** [comment]
Hi @gabbiere this was merged in ticket #192
