### ISSUE TITLE
setmaxtc fails to complete build

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco-mibs#54]
while trying to get the mib building bootstrap online, my builds keep on failing on the "compiling net-snmp" step.

logging output is:
Warning: -L../../snmplib/.libs changed to -L/root/.cpanm/work/1525536698.17459/Alien-SNMP-MAXTC-1.000001/_alien/net-snmp-5.7.3/perl/ASN/../../snmplib/.libs
Warning: -L../../snmplib/ changed to -L/root/.cpanm/work/1525536698.17459/Alien-SNMP-MAXTC-1.000001/_alien/net-snmp-5.7.3/perl/ASN/../../snmplib/
Unrecognized argument in LIBS ignored: '-fstack-protector-strong'
Writing MYMETA.yml and MYMETA.json
ERROR from evaluation of /root/.cpanm/work/1525536698.17459/Alien-SNMP-MAXTC-1.000001/_alien/net-snmp-5.7.3/perl/OID/**_Makefile.PL: panic: attempt to copy freed scalar 7fffec5171e0 to 7fffec654d18 at /usr/lib/perl5/5.26.1/Carp.pm line 229._**
Checking if your kit is complete...
Looks good
make: *** [Makefile:301: perlmakefiles] Error 2
External command (make) failed! Error: 512
 at ./Build line 66.
Failed
Build not completed at ./Build line 66.
-> FAIL Installing Alien::SNMP::MAXTC failed. See /root/.cpanm/work/1525536698.17459/build.log for details. Retry with --force to force install it.

(oh, and in this specific case i also forgot i was still in a root shell, but root or normal user did not make a difference)

this is on a debian buster (testing version) and opensuse tumbleweed (rolling release version). both of these however are running on windows 10 and the windows services for linux.

this seems however to be a known error and debian has provider a patch for this.
(https://sources.debian.org/data/main/n/net-snmp/5.7.3+dfsg-3/debian/patches/0001-CHANGES-BUG-2712-Fix-Perl-module-compilation.patch)

this however will make build continue but fail on typedef errors later. the kind people of debian have also provided us with a fix for this:
https://sources.debian.org/data/main/n/net-snmp/5.7.3+dfsg-3/debian/patches/0001-Remove-U64-typedef.patch

(also, you need to use the libssl-dev1.0, the standard libssl-1.1.0 is not compatible. for this as well debian has released patches but i did not try them: https://sources.debian.org/patches/net-snmp/5.7.3+dfsg-3/  )

the problem however for me is that setmaxtc is so beautifully automated that i didnt find a decent entrypoint to apply the patches. what i ended up doing was waiting till Alien-SNMP-MAXTC-1.000001 started building & then quickly apply the patches between net-snmp extraction & the start of the build. i guess the correct way would be to either put the patching stage in Alien-SNMP-MAXTC or provided a patched source file in the upstream-sources repo. once the build got solved the rest of the updating mibs wiki was smooth sailing. i'm now testing the vendor i added, there should be a patch incoming soon for that.

**Comment by inphobia** [comment]
since net-snmp 5.8 has been released i gave that a try, where MAXTC has been raised to 16384 in the default config. this seems to work without issue, went through the whole process to add 2 vendors & updating another, all went as expected.

frankenversion of alien-snmp-maxtc here:
https://github.com/inphobia/Alien-SNMP-MAXTC
(version 1.000004)

you also need to change the setmaxtc script to use that version instead of the default cpan one.

**Comment by JeroenvIS** [comment]
@ollyg Sounds like a good plan, updating to net-snmp 5.8. Especially now the MAXTC has been increased there.
Any downsides that you can think of?

**Comment by inphobia** [comment]
mentioning @ollyg since he is the cpan man for alien-snmp-maxtc

**Comment by inphobia** [comment]
fixed in 73f1f99220f71986bab9a44115ca66541a9accd2 , thx @ollyg  !
