### ISSUE TITLE
Add new MIBs from HPE

### ISSUE THREAD

**Issue by hrv231** [netdisco/netdisco-mibs#72]
Just wanted to provide the latest MIBs from HPE/Aruba
[ALL-Supported-MIBs.zip](https://github.com/netdisco/netdisco/files/2869983/ALL-Supported-MIBs.zip)

, this MIBs are not for their entire line of products, just for a few products.

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Environment

* Netdisco version used: 
* SNMP::Info version used:

**Comment by ollyg** [comment]
Thanks, I've added these under a new vendor directory "hpe":

````
[master 7df4534] #72 add HPE (Aruba Wired) MIBs
 13 files changed, 6987 insertions(+)
 create mode 100644 EXTRAS/indexes/cache/hpe
 create mode 100644 EXTRAS/reports/hpe
 create mode 100644 hpe/ARUBAWIRED-LOOPPROTECT-MIB.mib
 create mode 100644 hpe/ARUBAWIRED-MCLAG-MIB.mib
 create mode 100644 hpe/ARUBAWIRED-MGMD-RMON-TRAP-MIB.mib
 create mode 100644 hpe/ARUBAWIRED-MGMD-SNOOPING-MIB.mib
 create mode 100644 hpe/ARUBAWIRED-MVRP-MIB.mib
 create mode 100644 hpe/ARUBAWIRED-NETWORKING-OID.mib
 create mode 100644 hpe/ARUBAWIRED-RPVST-MIB.mib
 create mode 100644 hpe/ARUBAWIRED-VSX-MIB.mib
````
