### ISSUE TITLE
Add Qtech MIBs

### ISSUE THREAD

**Issue by anp135** [netdisco/netdisco-mibs#82]
Please add tht Qtech (QSW switches) MIBs for devices:

enterprises.27514.1.1.1.48
  QSW-2800-10T-AC Device, Compiled on Dec 25 04:27:39 2014
  SoftWare Version 7.0.3.5(R0217.0069)
  BootRom Version 7.1.3
  HardWare Version 1.0.1
  CPLD Version 1.2
  Copyright (C) 2014 by QTECH LLC

enterprises.27514.1.1.1.49
  QSW-2800-28T-AC Device, Compiled on Dec 25 04:27:39 2014
  SoftWare Version 7.0.3.5(R0217.0069)
  BootRom Version 7.1.3
  HardWare Version 1.0.2
  CPLD Version 1.2
  Copyright (C) 2014 by QTECH LLC

enterprises.40418.7.19
  SNR-S2985G-24T Device, Compiled on Mar 08 12:03:28 2017
  SoftWare Version 7.0.3.5(R0241.0145)
  BootRom Version 7.2.25
  HardWare Version 1.0.2
  CPLD Version N/A
  Copyright (C) 2017 NAG LLC

enterprises.40418.7.21
  SNR-S2985G-8T Device, Compiled on Jul 28 18:35:51 2015
  SoftWare Version 7.0.3.5(R0241.0053)
  BootRom Version 7.2.21
  HardWare Version 1.0.2
  CPLD Version N/A
  Copyright (C) 2011-2015 NAG LLC

enterprises.27514.1.1.1.337
  Device: QSW-2850-28T-AC, sysLocation: Crimea.
  SoftWare Version 1.1.5.6(Build245.139)
  BootRom Version  7.2.28
  HardWare Version 1.2
  CPLD Version     N/A
  Copyright (C) 2017 by QTECH LLC

enterprises.27514.1.1.2.40
  QSW-8300-52F Device, Compiled on Aug 03 14:51:32 2015
  SoftWare Version 7.0.3.1(R0244.0075)
  BootRom Version 7.1.107
  HardWare Version 1.0.2
  CPLD Version N/A
  Copyright (C) 2015 by QTECH LLC

enterprises.27514.1.1.2.54
  QSW-8200-52F-AC-DC Device, Compiled on Oct 20 09:19:33 2015
  SoftWare Version 7.0.3.1(R0244.0079)
  BootRom Version 7.1.107
  HardWare Version 1.0.2
  CPLD Version N/A
  Copyright (C) 2015 by QTECH LLC

enterprises.27514.1.280
  System device code  : G000032T00B17101302
  L2-hash mode: crc32
  QTECH Universal Software Platform
  USP (R) Software Version V210R220
  Copyright (c) 2000-2015, QTECH LLC
  Compiled Oct 13 2017,03:23:19
  QTECH QSW-2800-28T Switch
  Hardware Version : 1.0
  BIOS Version     : 1.2

**Comment by ollyg** [comment]
Hi @anp135 are the MIB files attached to the ticket or did you email them in? I can't see them.

**Comment by anp135** [comment]
[Qtech-mibs.zip](https://github.com/netdisco/netdisco-mibs/files/3104669/Qtech-mibs.zip)

**Comment by inphobia** [comment]
think these have not yet been added, i'll try and have a look in the coming days.

**Comment by anp135** [comment]
Thanks, but already done by myself.

**Comment by inphobia** [comment]
i've been trying to wrap my head around how qtech's mibs work.

for some switches they seem to have 1 file:
ftp://ftp.qtech.ru/Switch/Access/QSW-4610/MIB's/

for others they have a zip file with several mibs, all of them having a common sense name:
ftp://ftp.qtech.ru/Switch/Access/QSW-4600/MIB's/

and then they also have collections with the most generic names for both the files & mibs (mib name example: SWITCH-INVENTORY-MIB)
ftp://ftp.qtech.ru/Switch/Access/QSW-3310/MIB's/

on their ftp they have mibs for several product ranges as well:
* 27514 - seems to be used by their switch portfolio
* 34751 - is found in routing related mibs it seems.


@anp135 

can you give us some guidance on the structure of these mibs?

also, if you made an snmp::info module for these devices as your screenshot shows we would be very interested in adding these if you want to share the code.

**Comment by edo1** [comment]
@anp135 Have you added SNR switches support as well? I'm interested in it, could you share the patches?

**Comment by anp135** [comment]
@edo1, добавил в части базовых функций vendor/model/os/os_ver/serial. Это приводит к правильным группировкам в inventory по платформам и по софту, так как у китайского OEM (а это весь выводок "исконно русских" изделий от eltex, nag, qtech, rotek, ещё может кого забыл) часто один и тот же sysObjectID.0 - это по факту "4 разных человека"...

Более глубоко и полно я не запиливал, так как определение соседей в Netdisco работает совсем плохо, отображается ещё хуже, да и попытки использовать более, чем робота инвентаризации, приведёт к тому, что через три дня вы пишете уже NOC Project... а делать это на perl и через SNMP... - никому не говорите, иначе заберут в дурку... (как сильно я бы не уважал perl, познакомившись с ним лет 25 назад...).

В общем  anp135@yandex.ru, если перевод unknown / enterprise.8886... в vendor / model будет достаточно.

**Comment by ollyg** [comment]
> @edo1, added vendor / model / os / os_ver / serial in the base functions part. This leads to the correct groupings in inventory by platforms and software, since the Chinese OEM (and this is the entire brood of "primordially Russian" products from eltex, nag, qtech, rotek, maybe I forgot someone else) often has the same sysObjectID.0 - this is in fact "4 different people" ...
>  
> More deeply and fully I did not file, since the definition of neighbors in Netdisco works very badly, it is displayed even worse, and attempts to use more than an inventory robot will lead to the fact that in three days you are already writing a NOC Project ... but to do it's on perl and via SNMP ... - don't tell anyone, otherwise they will be taken away ... (how much I would not respect perl, having met him 25 years ago ...).
> 
> In general anp135@yandex.ru, if the translation unknown / enterprise.8886 ... in vendor / model will be enough.
