### ISSUE TITLE
Updated Extreme WING mib

### ISSUE THREAD

**Issue by cncolby** [netdisco/netdisco-mibs#83]
Hello - 

I have a more updated WING-MIB for Extreme Networks, as of 8/20/18. Downloaded under contract, would love to see it in netdisco.
[WING-MIB.zip](https://github.com/netdisco/netdisco-mibs/files/3096550/WING-MIB.zip)

**Comment by ollyg** [comment]
Thanks! committed in:
[master 28c7f36] #83 updated WING-MIB

_aside for devs:
the release date of the MIB was not updated, and also the MIB tries to branch from 'symbol' rather than 'wireless Products'. I fixed the latter (so genxlate diff is almost like-for-like)._
