### ISSUE TITLE
add Microsens G6 MIBS

### ISSUE THREAD

**Issue by ohilscher** [netdisco/netdisco-mibs#87]
Please add Microsens G6 MIBS for Ruggedized Switches
[G6_SNMP_MIBS.zip](https://github.com/netdisco/netdisco-mibs/files/3294550/G6_SNMP_MIBS.zip)

**Comment by inphobia** [comment]
seems to be pretty straightforward looking at the mibs, i'll give it a whirl later today.

do note that just adding the mibs is first part, but to actually use those private mibs a new class for snmp::info will also have to get made, which could be straightforward or a lot of work depending on the mib data relations.

**Comment by inphobia** [comment]
added in 44fe2e5

we did have to drop G6-ITU-NOTIFICATION-MIB.mib, since it had all the same definitions as MICROSENS-G6-NOTIFICATION-MIB but with a few changed descriptions. since it were trap definitions which we don't handle (yet) not relevant for us either.
