### ISSUE TITLE
New Cisco ASR-920-12SZ-IM device type

### ISSUE THREAD

**Issue by larryblunk** [netdisco/netdisco-mibs#91]
Missing MIB entry for Cisco product ASR-920-12SZ-IM

## Expected Behavior

need MIB entry for ASR-920-12SZ-IM

## Current Behavior

Model is not currently identified

## Possible Solution

Add entry for  .1.3.6.1.4.1.9.1.2247 for ASR-920-12SZ-IM

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Your Device

* Vendor: Cisco 
* Device Model:  ASR-920-12SZ-IM
* Operating System Version: 16.7.1
* Snmpwalk output of .1.3.6.1.2.1.1:
SNMPv2-MIB::sysDescr.0 = STRING: Cisco IOS Software [Fuji], ASR920 Software (PPC_LINUX_IOSD-UNIVERSALK9-M), Version 16.7.1, RELEASE SOFTWARE (fc6)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2017 by Cisco Systems, Inc.
Compiled Mon 20-Nov-17 17:28 by mcpre
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.9.1.2247
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (1449619505) 167 days, 18:43:15.05
SNMPv2-MIB::sysContact.0 = STRING: 
SNMPv2-MIB::sysName.0 = STRING: dtrt-dpl-campbell-e1.mich.net
SNMPv2-MIB::sysLocation.0 = STRING: 
SNMPv2-MIB::sysServices.0 = INTEGER: 6
SNMPv2-MIB::sysORLastChange.0 = Timeticks: (0) 0:00:00.00

## Your Environment

* SNMP::Info version used: 
* Netdisco version (if used):

**Comment by inphobia** [comment]
any luck with getting this added to the official products mib?

let us know, i have a pull request open with the latest product updates ( #95 ) which i'll be merging in a few days. if they refused your request we'll add this product manually for the time being.

**Comment by inphobia** [comment]
i'm moving all missing cisco product id's to #156 while we figure out a solution
