### ISSUE TITLE
Etherwan EX78900, EX73900, EX77900, EX77964 MIBS

### ISSUE THREAD

**Issue by smithdsl** [netdisco/netdisco-mibs#98]
[mib_v2.02.3.zip](https://github.com/netdisco/netdisco-mibs/files/3636716/mib_v2.02.3.zip)

**Comment by inphobia** [comment]
i had a look at their website and it seems 4.02.2 of their mib file is the most recent one and i think it should support your devices too.

**Comment by inphobia** [comment]
@smithdsl : could you let us know if version 4.02.0 which we added is sufficient for your needs?

**Comment by inphobia** [comment]
netdisco mibs 4.019 includes etherwan revision 201902210000Z, which should be newer as the one linked in this issue 201812040000Z.

let us know if you have any issues.
